- name: copy mongodb repo into yum.repos.d
  ansible.builtin.copy:
   src: mongodb.repo
   dest: /etc/yum.repos.d/mongodb.repo
- name: Install MongoDB
  ansible.builtin.yum:
   name: mongodb-org
   state: installed
- name: start and enable mongodb service 
  ansible.builtin.service:
   name: mongod
   state: started
   enabled: true
- name: enable remote connections mongodb
  ansible.builtin.replace:
   path: /etc/mongod.conf
   regexp: '127.0.0.1'
   replace: '0.0.0.0'
- name: restart mongod service
  ansible.builtin.service:
   name: mongod
   state: restarted