- name: Install NodeJS
  ansible.builtin.import_role:
   name: common
   tasks_from: nodejs

- name: Setup Application
  ansible.builtin.import_role:
   name: common
   tasks_from: app-setup

- name: Install dependencies
  ansible.builtin.command: npm install
  args:
   chdir: /app

- name: Load shcema(user data)
  ansible.builtin.import_role:
   name: common
   tasks_from: load-mongo-schema

- name: Start Application
  ansible.builtin.import_role:
   name: common
   tasks_from: systemd-setup