- name: copy mongodb.repo into yum.repos.d
  ansible.builtin.copy:
   src: mongodb.repo
   dest: /etc/yum.repos.d/mongodb.repo

- name: Install mongodb client package
  ansible.builtin.yum:
   name: mongodb-org-shell
   state: installed

- name: Load {{component}} data
  ansible.builtin.shell: mongo --host mongodb.sivadevops.website </app/schema/{{component}}.js