- name: Install mysql
  ansible.builtin.yum:
   name: mysql
   state: installed

- name: load mysql schema
  ansible.builtin.shell: mysql -h mysql.sivadevops.website -uroot -pRoboShop@1 < /app/schema/{{component}}.sql 